# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.6
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pychrm', [dirname(__file__)])
        except ImportError:
            import _pychrm
            return _pychrm
        if fp is not None:
            try:
                _mod = imp.load_module('_pychrm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pychrm = swig_import_helper()
    del swig_import_helper
else:
    import _pychrm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


cmRGB = _pychrm.cmRGB
cmHSV = _pychrm.cmHSV
INF = _pychrm.INF
class RGBcolor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RGBcolor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RGBcolor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["red"] = _pychrm.RGBcolor_red_set
    __swig_getmethods__["red"] = _pychrm.RGBcolor_red_get
    if _newclass:red = _swig_property(_pychrm.RGBcolor_red_get, _pychrm.RGBcolor_red_set)
    __swig_setmethods__["green"] = _pychrm.RGBcolor_green_set
    __swig_getmethods__["green"] = _pychrm.RGBcolor_green_get
    if _newclass:green = _swig_property(_pychrm.RGBcolor_green_get, _pychrm.RGBcolor_green_set)
    __swig_setmethods__["blue"] = _pychrm.RGBcolor_blue_set
    __swig_getmethods__["blue"] = _pychrm.RGBcolor_blue_get
    if _newclass:blue = _swig_property(_pychrm.RGBcolor_blue_get, _pychrm.RGBcolor_blue_set)
    def __init__(self): 
        this = _pychrm.new_RGBcolor()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_RGBcolor
    __del__ = lambda self : None;
RGBcolor_swigregister = _pychrm.RGBcolor_swigregister
RGBcolor_swigregister(RGBcolor)

class HSVcolor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HSVcolor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HSVcolor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["hue"] = _pychrm.HSVcolor_hue_set
    __swig_getmethods__["hue"] = _pychrm.HSVcolor_hue_get
    if _newclass:hue = _swig_property(_pychrm.HSVcolor_hue_get, _pychrm.HSVcolor_hue_set)
    __swig_setmethods__["saturation"] = _pychrm.HSVcolor_saturation_set
    __swig_getmethods__["saturation"] = _pychrm.HSVcolor_saturation_get
    if _newclass:saturation = _swig_property(_pychrm.HSVcolor_saturation_get, _pychrm.HSVcolor_saturation_set)
    __swig_setmethods__["value"] = _pychrm.HSVcolor_value_set
    __swig_getmethods__["value"] = _pychrm.HSVcolor_value_get
    if _newclass:value = _swig_property(_pychrm.HSVcolor_value_get, _pychrm.HSVcolor_value_set)
    def __init__(self): 
        this = _pychrm.new_HSVcolor()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_HSVcolor
    __del__ = lambda self : None;
HSVcolor_swigregister = _pychrm.HSVcolor_swigregister
HSVcolor_swigregister(HSVcolor)

class color(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, color, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, color, name)
    __repr__ = _swig_repr
    __swig_setmethods__["RGB"] = _pychrm.color_RGB_set
    __swig_getmethods__["RGB"] = _pychrm.color_RGB_get
    if _newclass:RGB = _swig_property(_pychrm.color_RGB_get, _pychrm.color_RGB_set)
    __swig_setmethods__["HSV"] = _pychrm.color_HSV_set
    __swig_getmethods__["HSV"] = _pychrm.color_HSV_get
    if _newclass:HSV = _swig_property(_pychrm.color_HSV_get, _pychrm.color_HSV_set)
    def __init__(self): 
        this = _pychrm.new_color()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_color
    __del__ = lambda self : None;
color_swigregister = _pychrm.color_swigregister
color_swigregister(color)

class pix_data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, pix_data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, pix_data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["clr"] = _pychrm.pix_data_clr_set
    __swig_getmethods__["clr"] = _pychrm.pix_data_clr_get
    if _newclass:clr = _swig_property(_pychrm.pix_data_clr_get, _pychrm.pix_data_clr_set)
    __swig_setmethods__["intensity"] = _pychrm.pix_data_intensity_set
    __swig_getmethods__["intensity"] = _pychrm.pix_data_intensity_get
    if _newclass:intensity = _swig_property(_pychrm.pix_data_intensity_get, _pychrm.pix_data_intensity_set)
    def __init__(self): 
        this = _pychrm.new_pix_data()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_pix_data
    __del__ = lambda self : None;
pix_data_swigregister = _pychrm.pix_data_swigregister
pix_data_swigregister(pix_data)

class rect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rect, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _pychrm.rect_x_set
    __swig_getmethods__["x"] = _pychrm.rect_x_get
    if _newclass:x = _swig_property(_pychrm.rect_x_get, _pychrm.rect_x_set)
    __swig_setmethods__["y"] = _pychrm.rect_y_set
    __swig_getmethods__["y"] = _pychrm.rect_y_get
    if _newclass:y = _swig_property(_pychrm.rect_y_get, _pychrm.rect_y_set)
    __swig_setmethods__["w"] = _pychrm.rect_w_set
    __swig_getmethods__["w"] = _pychrm.rect_w_get
    if _newclass:w = _swig_property(_pychrm.rect_w_get, _pychrm.rect_w_set)
    __swig_setmethods__["h"] = _pychrm.rect_h_set
    __swig_getmethods__["h"] = _pychrm.rect_h_get
    if _newclass:h = _swig_property(_pychrm.rect_h_get, _pychrm.rect_h_set)
    def __init__(self): 
        this = _pychrm.new_rect()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_rect
    __del__ = lambda self : None;
rect_swigregister = _pychrm.rect_swigregister
rect_swigregister(rect)


def compare_doubles(*args):
  return _pychrm.compare_doubles(*args)
compare_doubles = _pychrm.compare_doubles
class ImageMatrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageMatrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ImageMatrix, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _pychrm.ImageMatrix_data_set
    __swig_getmethods__["data"] = _pychrm.ImageMatrix_data_get
    if _newclass:data = _swig_property(_pychrm.ImageMatrix_data_get, _pychrm.ImageMatrix_data_set)
    __swig_setmethods__["ColorMode"] = _pychrm.ImageMatrix_ColorMode_set
    __swig_getmethods__["ColorMode"] = _pychrm.ImageMatrix_ColorMode_get
    if _newclass:ColorMode = _swig_property(_pychrm.ImageMatrix_ColorMode_get, _pychrm.ImageMatrix_ColorMode_set)
    __swig_setmethods__["bits"] = _pychrm.ImageMatrix_bits_set
    __swig_getmethods__["bits"] = _pychrm.ImageMatrix_bits_get
    if _newclass:bits = _swig_property(_pychrm.ImageMatrix_bits_get, _pychrm.ImageMatrix_bits_set)
    __swig_setmethods__["width"] = _pychrm.ImageMatrix_width_set
    __swig_getmethods__["width"] = _pychrm.ImageMatrix_width_get
    if _newclass:width = _swig_property(_pychrm.ImageMatrix_width_get, _pychrm.ImageMatrix_width_set)
    __swig_setmethods__["height"] = _pychrm.ImageMatrix_height_set
    __swig_getmethods__["height"] = _pychrm.ImageMatrix_height_get
    if _newclass:height = _swig_property(_pychrm.ImageMatrix_height_get, _pychrm.ImageMatrix_height_set)
    __swig_setmethods__["depth"] = _pychrm.ImageMatrix_depth_set
    __swig_getmethods__["depth"] = _pychrm.ImageMatrix_depth_get
    if _newclass:depth = _swig_property(_pychrm.ImageMatrix_depth_get, _pychrm.ImageMatrix_depth_set)
    def LoadTIFF(self, *args): return _pychrm.ImageMatrix_LoadTIFF(self, *args)
    def SaveTiff(self, *args): return _pychrm.ImageMatrix_SaveTiff(self, *args)
    def LoadPPM(self, *args): return _pychrm.ImageMatrix_LoadPPM(self, *args)
    def OpenImage(self, *args): return _pychrm.ImageMatrix_OpenImage(self, *args)
    def __init__(self, *args): 
        this = _pychrm.new_ImageMatrix(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_ImageMatrix
    __del__ = lambda self : None;
    def duplicate(self): return _pychrm.ImageMatrix_duplicate(self)
    def pixel(self, *args): return _pychrm.ImageMatrix_pixel(self, *args)
    def set(self, *args): return _pychrm.ImageMatrix_set(self, *args)
    def SetInt(self, *args): return _pychrm.ImageMatrix_SetInt(self, *args)
    def diff(self, *args): return _pychrm.ImageMatrix_diff(self, *args)
    def normalize(self, *args): return _pychrm.ImageMatrix_normalize(self, *args)
    def to8bits(self): return _pychrm.ImageMatrix_to8bits(self)
    def flip(self): return _pychrm.ImageMatrix_flip(self)
    def invert(self): return _pychrm.ImageMatrix_invert(self)
    def Downsample(self, *args): return _pychrm.ImageMatrix_Downsample(self, *args)
    def Rotate(self, *args): return _pychrm.ImageMatrix_Rotate(self, *args)
    def convolve(self, *args): return _pychrm.ImageMatrix_convolve(self, *args)
    def BasicStatistics(self, *args): return _pychrm.ImageMatrix_BasicStatistics(self, *args)
    def GetColorStatistics(self, *args): return _pychrm.ImageMatrix_GetColorStatistics(self, *args)
    def ColorTransform(self, *args): return _pychrm.ImageMatrix_ColorTransform(self, *args)
    def histogram(self, *args): return _pychrm.ImageMatrix_histogram(self, *args)
    def Otsu(self): return _pychrm.ImageMatrix_Otsu(self)
    def MultiScaleHistogram(self, *args): return _pychrm.ImageMatrix_MultiScaleHistogram(self, *args)
    def EdgeTransform(self): return _pychrm.ImageMatrix_EdgeTransform(self)
    def fft2(self): return _pychrm.ImageMatrix_fft2(self)
    def ChebyshevTransform(self, *args): return _pychrm.ImageMatrix_ChebyshevTransform(self, *args)
    def ChebyshevFourierTransform2D(self, *args): return _pychrm.ImageMatrix_ChebyshevFourierTransform2D(self, *args)
    def Symlet5Transform(self): return _pychrm.ImageMatrix_Symlet5Transform(self)
    def GradientMagnitude(self, *args): return _pychrm.ImageMatrix_GradientMagnitude(self, *args)
    def GradientDirection2D(self, *args): return _pychrm.ImageMatrix_GradientDirection2D(self, *args)
    def PerwittMagnitude2D(self, *args): return _pychrm.ImageMatrix_PerwittMagnitude2D(self, *args)
    def PerwittDirection2D(self, *args): return _pychrm.ImageMatrix_PerwittDirection2D(self, *args)
    def ChebyshevStatistics2D(self, *args): return _pychrm.ImageMatrix_ChebyshevStatistics2D(self, *args)
    def CombFirstFourMoments2D(self, *args): return _pychrm.ImageMatrix_CombFirstFourMoments2D(self, *args)
    def EdgeStatistics(self, *args): return _pychrm.ImageMatrix_EdgeStatistics(self, *args)
    def RadonTransform2D(self, *args): return _pychrm.ImageMatrix_RadonTransform2D(self, *args)
    def OtsuBinaryMaskTransform(self): return _pychrm.ImageMatrix_OtsuBinaryMaskTransform(self)
    def BWlabel(self, *args): return _pychrm.ImageMatrix_BWlabel(self, *args)
    def centroid(self, *args): return _pychrm.ImageMatrix_centroid(self, *args)
    def FeatureStatistics(self, *args): return _pychrm.ImageMatrix_FeatureStatistics(self, *args)
    def GaborFilters2D(self, *args): return _pychrm.ImageMatrix_GaborFilters2D(self, *args)
    def HaarlickTexture2D(self, *args): return _pychrm.ImageMatrix_HaarlickTexture2D(self, *args)
    def TamuraTexture2D(self, *args): return _pychrm.ImageMatrix_TamuraTexture2D(self, *args)
    def zernike2D(self, *args): return _pychrm.ImageMatrix_zernike2D(self, *args)
ImageMatrix_swigregister = _pychrm.ImageMatrix_swigregister
ImageMatrix_swigregister(ImageMatrix)


def RGB2HSV(*args):
  return _pychrm.RGB2HSV(*args)
RGB2HSV = _pychrm.RGB2HSV

def HSV2RGB(*args):
  return _pychrm.HSV2RGB(*args)
HSV2RGB = _pychrm.HSV2RGB

def RGB2COLOR(*args):
  return _pychrm.RGB2COLOR(*args)
RGB2COLOR = _pychrm.RGB2COLOR

def COLOR2GRAY(*args):
  return _pychrm.COLOR2GRAY(*args)
COLOR2GRAY = _pychrm.COLOR2GRAY
WC_UNINITIALIZED = _pychrm.WC_UNINITIALIZED
WC_NO_ERROR = _pychrm.WC_NO_ERROR
WC_IPP_NULL = _pychrm.WC_IPP_NULL
WC_MM_FAIL_RECURSIVE_CALL = _pychrm.WC_MM_FAIL_RECURSIVE_CALL
WC_TRANSFORM_FAIL = _pychrm.WC_TRANSFORM_FAIL
WC_EMPTY = _pychrm.WC_EMPTY
WC_NOT_IMPLEMENTED = _pychrm.WC_NOT_IMPLEMENTED
WC_INPUT_IMAGEMATRIX_NULL = _pychrm.WC_INPUT_IMAGEMATRIX_NULL

def catError(*args):
  return _pychrm.catError(*args)
catError = _pychrm.catError

def showError(*args):
  return _pychrm.showError(*args)
showError = _pychrm.showError

def getErrorString():
  return _pychrm.getErrorString()
getErrorString = _pychrm.getErrorString

def translateError(*args):
  return _pychrm.translateError(*args)
translateError = _pychrm.translateError
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pychrm.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _pychrm.SwigPyIterator_value(self)
    def incr(self, n=1): return _pychrm.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _pychrm.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _pychrm.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _pychrm.SwigPyIterator_equal(self, *args)
    def copy(self): return _pychrm.SwigPyIterator_copy(self)
    def next(self): return _pychrm.SwigPyIterator_next(self)
    def __next__(self): return _pychrm.SwigPyIterator___next__(self)
    def previous(self): return _pychrm.SwigPyIterator_previous(self)
    def advance(self, *args): return _pychrm.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _pychrm.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _pychrm.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _pychrm.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _pychrm.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _pychrm.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _pychrm.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _pychrm.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _pychrm.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _pychrm.DoubleVector___nonzero__(self)
    def __bool__(self): return _pychrm.DoubleVector___bool__(self)
    def __len__(self): return _pychrm.DoubleVector___len__(self)
    def pop(self): return _pychrm.DoubleVector_pop(self)
    def __getslice__(self, *args): return _pychrm.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _pychrm.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _pychrm.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _pychrm.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _pychrm.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _pychrm.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _pychrm.DoubleVector_append(self, *args)
    def empty(self): return _pychrm.DoubleVector_empty(self)
    def size(self): return _pychrm.DoubleVector_size(self)
    def clear(self): return _pychrm.DoubleVector_clear(self)
    def swap(self, *args): return _pychrm.DoubleVector_swap(self, *args)
    def get_allocator(self): return _pychrm.DoubleVector_get_allocator(self)
    def begin(self): return _pychrm.DoubleVector_begin(self)
    def end(self): return _pychrm.DoubleVector_end(self)
    def rbegin(self): return _pychrm.DoubleVector_rbegin(self)
    def rend(self): return _pychrm.DoubleVector_rend(self)
    def pop_back(self): return _pychrm.DoubleVector_pop_back(self)
    def erase(self, *args): return _pychrm.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _pychrm.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _pychrm.DoubleVector_push_back(self, *args)
    def front(self): return _pychrm.DoubleVector_front(self)
    def back(self): return _pychrm.DoubleVector_back(self)
    def assign(self, *args): return _pychrm.DoubleVector_assign(self, *args)
    def resize(self, *args): return _pychrm.DoubleVector_resize(self, *args)
    def insert(self, *args): return _pychrm.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _pychrm.DoubleVector_reserve(self, *args)
    def capacity(self): return _pychrm.DoubleVector_capacity(self)
    __swig_destroy__ = _pychrm.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _pychrm.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class FeatureAlgorithm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FeatureAlgorithm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FeatureAlgorithm, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _pychrm.FeatureAlgorithm_name_set
    __swig_getmethods__["name"] = _pychrm.FeatureAlgorithm_name_get
    if _newclass:name = _swig_property(_pychrm.FeatureAlgorithm_name_get, _pychrm.FeatureAlgorithm_name_set)
    __swig_setmethods__["n_features"] = _pychrm.FeatureAlgorithm_n_features_set
    __swig_getmethods__["n_features"] = _pychrm.FeatureAlgorithm_n_features_get
    if _newclass:n_features = _swig_property(_pychrm.FeatureAlgorithm_n_features_get, _pychrm.FeatureAlgorithm_n_features_set)
    def calculate(self, *args): return _pychrm.FeatureAlgorithm_calculate(self, *args)
    def print_info(self): return _pychrm.FeatureAlgorithm_print_info(self)
    __swig_destroy__ = _pychrm.delete_FeatureAlgorithm
    __del__ = lambda self : None;
FeatureAlgorithm_swigregister = _pychrm.FeatureAlgorithm_swigregister
FeatureAlgorithm_swigregister(FeatureAlgorithm)

class EmptyFeatureAlgorithm(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EmptyFeatureAlgorithm, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EmptyFeatureAlgorithm, name)
    __repr__ = _swig_repr
    def calculate(self, *args): return _pychrm.EmptyFeatureAlgorithm_calculate(self, *args)
    def __init__(self, *args): 
        this = _pychrm.new_EmptyFeatureAlgorithm(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pychrm.delete_EmptyFeatureAlgorithm
    __del__ = lambda self : None;
EmptyFeatureAlgorithm_swigregister = _pychrm.EmptyFeatureAlgorithm_swigregister
EmptyFeatureAlgorithm_swigregister(EmptyFeatureAlgorithm)

class ChebyshevFourierCoefficients(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ChebyshevFourierCoefficients, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ChebyshevFourierCoefficients, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ChebyshevFourierCoefficients()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.ChebyshevFourierCoefficients_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_ChebyshevFourierCoefficients
    __del__ = lambda self : None;
ChebyshevFourierCoefficients_swigregister = _pychrm.ChebyshevFourierCoefficients_swigregister
ChebyshevFourierCoefficients_swigregister(ChebyshevFourierCoefficients)

class ChebyshevCoefficients(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ChebyshevCoefficients, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ChebyshevCoefficients, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ChebyshevCoefficients()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.ChebyshevCoefficients_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_ChebyshevCoefficients
    __del__ = lambda self : None;
ChebyshevCoefficients_swigregister = _pychrm.ChebyshevCoefficients_swigregister
ChebyshevCoefficients_swigregister(ChebyshevCoefficients)

class ZernikeCoefficients(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ZernikeCoefficients, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ZernikeCoefficients, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ZernikeCoefficients()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.ZernikeCoefficients_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_ZernikeCoefficients
    __del__ = lambda self : None;
ZernikeCoefficients_swigregister = _pychrm.ZernikeCoefficients_swigregister
ZernikeCoefficients_swigregister(ZernikeCoefficients)

class HaralickTextures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HaralickTextures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HaralickTextures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_HaralickTextures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.HaralickTextures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_HaralickTextures
    __del__ = lambda self : None;
HaralickTextures_swigregister = _pychrm.HaralickTextures_swigregister
HaralickTextures_swigregister(HaralickTextures)

class MultiscaleHistograms(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MultiscaleHistograms, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, MultiscaleHistograms, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_MultiscaleHistograms()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.MultiscaleHistograms_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_MultiscaleHistograms
    __del__ = lambda self : None;
MultiscaleHistograms_swigregister = _pychrm.MultiscaleHistograms_swigregister
MultiscaleHistograms_swigregister(MultiscaleHistograms)

class TamuraTextures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TamuraTextures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TamuraTextures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_TamuraTextures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.TamuraTextures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_TamuraTextures
    __del__ = lambda self : None;
TamuraTextures_swigregister = _pychrm.TamuraTextures_swigregister
TamuraTextures_swigregister(TamuraTextures)

class CombFirstFourMoments(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CombFirstFourMoments, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CombFirstFourMoments, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_CombFirstFourMoments()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.CombFirstFourMoments_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_CombFirstFourMoments
    __del__ = lambda self : None;
CombFirstFourMoments_swigregister = _pychrm.CombFirstFourMoments_swigregister
CombFirstFourMoments_swigregister(CombFirstFourMoments)

class RadonCoefficients(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RadonCoefficients, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, RadonCoefficients, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_RadonCoefficients()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.RadonCoefficients_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_RadonCoefficients
    __del__ = lambda self : None;
RadonCoefficients_swigregister = _pychrm.RadonCoefficients_swigregister
RadonCoefficients_swigregister(RadonCoefficients)

class FractalFeatures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FractalFeatures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FractalFeatures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_FractalFeatures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.FractalFeatures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_FractalFeatures
    __del__ = lambda self : None;
FractalFeatures_swigregister = _pychrm.FractalFeatures_swigregister
FractalFeatures_swigregister(FractalFeatures)

class PixelIntensityStatistics(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PixelIntensityStatistics, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PixelIntensityStatistics, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_PixelIntensityStatistics()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.PixelIntensityStatistics_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_PixelIntensityStatistics
    __del__ = lambda self : None;
PixelIntensityStatistics_swigregister = _pychrm.PixelIntensityStatistics_swigregister
PixelIntensityStatistics_swigregister(PixelIntensityStatistics)

class EdgeFeatures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EdgeFeatures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EdgeFeatures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_EdgeFeatures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.EdgeFeatures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_EdgeFeatures
    __del__ = lambda self : None;
EdgeFeatures_swigregister = _pychrm.EdgeFeatures_swigregister
EdgeFeatures_swigregister(EdgeFeatures)

class ObjectFeatures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ObjectFeatures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ObjectFeatures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ObjectFeatures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.ObjectFeatures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_ObjectFeatures
    __del__ = lambda self : None;
ObjectFeatures_swigregister = _pychrm.ObjectFeatures_swigregister
ObjectFeatures_swigregister(ObjectFeatures)

class GaborTextures(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GaborTextures, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GaborTextures, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_GaborTextures()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.GaborTextures_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_GaborTextures
    __del__ = lambda self : None;
GaborTextures_swigregister = _pychrm.GaborTextures_swigregister
GaborTextures_swigregister(GaborTextures)

class GiniCoefficient(FeatureAlgorithm):
    __swig_setmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GiniCoefficient, name, value)
    __swig_getmethods__ = {}
    for _s in [FeatureAlgorithm]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GiniCoefficient, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_GiniCoefficient()
        try: self.this.append(this)
        except: self.this = this
    def calculate(self, *args): return _pychrm.GiniCoefficient_calculate(self, *args)
    __swig_destroy__ = _pychrm.delete_GiniCoefficient
    __del__ = lambda self : None;
GiniCoefficient_swigregister = _pychrm.GiniCoefficient_swigregister
GiniCoefficient_swigregister(GiniCoefficient)

class Transform(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Transform, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Transform, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def transform(self, *args): return _pychrm.Transform_transform(self, *args)
    __swig_setmethods__["name"] = _pychrm.Transform_name_set
    __swig_getmethods__["name"] = _pychrm.Transform_name_get
    if _newclass:name = _swig_property(_pychrm.Transform_name_get, _pychrm.Transform_name_set)
    def print_info(self): return _pychrm.Transform_print_info(self)
    __swig_destroy__ = _pychrm.delete_Transform
    __del__ = lambda self : None;
Transform_swigregister = _pychrm.Transform_swigregister
Transform_swigregister(Transform)

class EmptyTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EmptyTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EmptyTransform, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _pychrm.new_EmptyTransform(*args)
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.EmptyTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_EmptyTransform
    __del__ = lambda self : None;
EmptyTransform_swigregister = _pychrm.EmptyTransform_swigregister
EmptyTransform_swigregister(EmptyTransform)

class FourierTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FourierTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FourierTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_FourierTransform()
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.FourierTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_FourierTransform
    __del__ = lambda self : None;
FourierTransform_swigregister = _pychrm.FourierTransform_swigregister
FourierTransform_swigregister(FourierTransform)

class ChebyshevTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ChebyshevTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ChebyshevTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ChebyshevTransform()
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.ChebyshevTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_ChebyshevTransform
    __del__ = lambda self : None;
ChebyshevTransform_swigregister = _pychrm.ChebyshevTransform_swigregister
ChebyshevTransform_swigregister(ChebyshevTransform)

class WaveletTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, WaveletTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, WaveletTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_WaveletTransform()
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.WaveletTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_WaveletTransform
    __del__ = lambda self : None;
WaveletTransform_swigregister = _pychrm.WaveletTransform_swigregister
WaveletTransform_swigregister(WaveletTransform)

class EdgeTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EdgeTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, EdgeTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_EdgeTransform()
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.EdgeTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_EdgeTransform
    __del__ = lambda self : None;
EdgeTransform_swigregister = _pychrm.EdgeTransform_swigregister
EdgeTransform_swigregister(EdgeTransform)

class ColorTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ColorTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ColorTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_ColorTransform()
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["histogram_vals"] = _pychrm.ColorTransform_histogram_vals_set
    __swig_getmethods__["histogram_vals"] = _pychrm.ColorTransform_histogram_vals_get
    if _newclass:histogram_vals = _swig_property(_pychrm.ColorTransform_histogram_vals_get, _pychrm.ColorTransform_histogram_vals_set)
    def transform(self, *args): return _pychrm.ColorTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_ColorTransform
    __del__ = lambda self : None;
ColorTransform_swigregister = _pychrm.ColorTransform_swigregister
ColorTransform_swigregister(ColorTransform)

class HueTransform(Transform):
    __swig_setmethods__ = {}
    for _s in [Transform]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HueTransform, name, value)
    __swig_getmethods__ = {}
    for _s in [Transform]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HueTransform, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pychrm.new_HueTransform()
        try: self.this.append(this)
        except: self.this = this
    def transform(self, *args): return _pychrm.HueTransform_transform(self, *args)
    __swig_destroy__ = _pychrm.delete_HueTransform
    __del__ = lambda self : None;
HueTransform_swigregister = _pychrm.HueTransform_swigregister
HueTransform_swigregister(HueTransform)

# This file is compatible with both classic and new-style classes.


